version: '3'
services:
  web:
    build: 
      context: src/simple-api
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    command:
      - "dotnet simple-api.dll" 
    environment:
      - Redis__Host=simple-api-redis
    links:
      - redis
  redis:
    container_name: simple-api-redis
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    restart: always